# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Simple Navigation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftLocation'
  
  # Pods for Simple Navigation

  target 'Simple NavigationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Simple NavigationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
